version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"      
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/data.db:/backend/data.db
    networks:
      - app-network


networks:
  app-network:
    driver: bridge